version: "3.5"

networks:
  app-tier:
    driver: bridge

volumes:
  data:

services:
  front-end:
    container_name: mean-front-end
    build:
      context: .
      dockerfile: ./front-end/mean-example/Dockerfile
    volumes:
      - "./front-end/mean-example:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - app-tier
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - back-end
  back-end:
    container_name: mean-back-end
    build:
      context: .
      dockerfile: ./back-end/mean-example/Dockerfile
    volumes:
      - "./back-end/mean-example:/usr/src/app"
    networks:
      - app-tier
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  mongodb:
    image: "bitnami/mongodb:latest"
    container_name: mean-mongo
    networks:
      - app-tier
    ports:
      - "27018:27018"
    volumes:
      - data:/bitnami
    environment:
      - MONGODB_ROOT_PASSWORD=root123
      - MONGODB_USERNAME=mean-example
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=mean-example
      - MONGODB_PORT_NUMBER=27018
